$(function() {
    $("#list1").click(function() {
        $("#form_in0").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in1").show()

    })
    $("#list2").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in2").show()
    })
    $("#list3").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in3").show()
    })
    $("#list4").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in4").show()
    })
    $("#list5").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in5").show()
    })
    $("#list6").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in6").show()
    })
    $("#list7").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in7").show()
    })
    $("#list8").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in8").show()
    })
    $("#list9").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in10").hide()
        $("#form_in11").hide()
        $("#form_in9").show()
    })
    $("#list10").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in11").hide()
        $("#form_in10").show()
    })

    $("#list11").click(function() {
        $("#form_in0").hide()
        $("#form_in1").hide()
        $("#form_in2").hide()
        $("#form_in3").hide()
        $("#form_in4").hide()
        $("#form_in5").hide()
        $("#form_in6").hide()
        $("#form_in7").hide()
        $("#form_in8").hide()
        $("#form_in9").hide()
        $("#form_in10").hide()
        $("#form_in11").show()
    })

    $("#userMessage").click(function () {
        $("#form_in9").show()
    })
    $("#close").click(function () {
        $("#form_in9").hide()
    })

    $("#schoolMes").click(function () {
        $("#form_in10").show()
    })
    $("#closes").click(function () {
        $("#form_in10").hide()
    })
})